### ISSUE TITLE
Installation error 

### ISSUE THREAD

**Issue by Mahende** [Azure/aimtool#24]
## Description

Please explain the issue or feature request, giving as much context as you can.
Hi team i am having issue installing aimtool in my staging server 
Below are error received 

PS C:\WINDOWS\system32> choco search biztalkmigrator --pre
Chocolatey v0.10.15
biztalkmigrator 0.5.1-beta-2020102860429 - Possibly broken
biztalkmigrator-biztalk 0.5.1-beta-2020102860429
biztalkmigrator-cli 0.5.1-beta-2020102844785
biztalkmigrator-azure 0.5.1-beta-2020102943006

During installation , it get terminated as below information 
2021-07-10 17:26:19,127 9564 [INFO ] - biztalkmigrator package files install completed. Performing other installation steps.
2021-07-10 17:26:19,131 9564 [DEBUG] - No package information as package is null.
2021-07-10 17:26:19,146 9564 [DEBUG] - No package information to save as package is null.
2021-07-10 17:26:19,149 9564 [DEBUG] - Sending message 'HandlePackageResultCompletedMessage' out if there are subscribers...
2021-07-10 17:26:19,151 9564 [ERROR] - The install of biztalkmigrator was NOT successful.
2021-07-10 17:26:19,153 9564 [ERROR] - biztalkmigrator not installed. An error occurred during installation:
 The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
2021-07-10 17:26:19,161 9564 [WARN ] - 
Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
[chocolatey.log](https://github.com/Azure/aimtool/files/6798699/chocolatey.log)

## Environment and tool versions
- AIM Tool Version (aim --version): 
- Windows Version (systeminfo):
- Shell: (PowerShell | Bash)
- Shell Version ($PSVersionTable | bash --version): 

## Repro steps

Please list out the steps needed to repro the issue, or delete if this is a feature request.

## Expected result

Please describe what you expected to see, or delete if this is a feature request.

## Current result

Please describe what you are seeing, or delete if this is a feature request.

**Comment by probertdaniel** [comment]
Thanks, @Mahende.
That looks like a Chocolatey error, rather than a tool error - at a guess, the path where chocolatey is installing the tool is more than 260 chars long.
Can you confirm where chocolatey is installed? In a default install, it's installed here: C:\ProgramData\chocolatey

**Comment by tobiasoort** [comment]
For future reference: this happens because chocolatey uses your tempdir as a download cache. If your username is long then the whole path will be long (because its in %USERPROFILE%).

So, easy fix: make a directory 'cc' on the root drive, and then run
```
choco config set cacheLocation c:\cc
```
per the docs at https://docs.chocolatey.org/en-us/guides/usage/change-cache.

Then it installs just fine. 

Also, it seems that it is Nuget that is still limited to 260 chars maxlength. They seem to have fixed this: https://github.com/NuGet/Home/issues/3324

So perhaps package a newer Nuget executable in the Choco package?

**Comment by probertdaniel** [comment]
Thanks, Tobias, that's really useful.
We're hoping to move away from Chocolatey and start using Windows Package Manager (wpm/winget) which means we have a new MSI for install, which we'll make available for download soon.
