### ISSUE TITLE
 target  does not have standard logic app option  --target <Consumption|Ise>

### ISSUE THREAD

**Issue by dassuresh** [Azure/aimtool#25]
## Description

Please explain the issue or feature request, giving as much context as you can.

## Environment and tool versions

- AIM Tool Version (aim --version): 
- Windows Version (systeminfo):
- Shell: (PowerShell | Bash)
- Shell Version ($PSVersionTable | bash --version): 

## Repro steps

Please list out the steps needed to repro the issue, or delete if this is a feature request.

## Expected result

Please describe what you expected to see, or delete if this is a feature request.

## Current result

Please describe what you are seeing, or delete if this is a feature request.

**Comment by probertdaniel** [comment]
Hi Dassruesh - I'm not sure what the issue you're logging is? The current version of the tool doesn't support Standard, it's coming very soon though. I'll assume that you're asking "Where is Standard support?". We're waiting on some bug fixes to the Standard runtime before we release the updated version of the tooling. Thanks for your interest, though!
